services:
  directus:
    container_name: csd223-lab5
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
      - ./extensions:/directus/extensions
    networks: 
      - directus

    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/chinook.sqlite'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'

networks:
  directus:
